//! `tuipo config` — interactive TUI editor for
//! `~/.config/tuipo/config.toml`.
//!
//! Sibling to `tuipo init`. Lists every setting on one screen, navigates
//! with arrow keys, toggles bools/enums with space, edits numbers/strings
//! in place, saves to disk with `s`, exits with `q` (with a confirm
//! prompt when there are unsaved changes).
//!
//! ## Why hand-roll instead of using ratatui
//!
//! The form has eight fields. The UI is fully static — no scrolling, no
//! resizing logic beyond "render once per event." Adding ratatui as a
//! dependency would buy borders + flex layout we don't need and bloat
//! the binary. `crossterm` (already a dep) gives us all we need: raw
//! mode, alt screen, cursor positioning, key events, color/style.
//!
//! ## Subcommand modes
//!
//! - `tuipo config`             — interactive TUI (this module).
//! - `tuipo config --print`     — dump current config as TOML to stdout.
//! - `tuipo config --path`      — print the config file path.
//! - `tuipo config --dry-run`   — same as TUI; `s` prints to stdout
//!   instead of writing the file. Useful for testing without touching
//!   `~/.config/tuipo/config.toml`.
//!
//! `--print` and `--path` are useful for scripts and quick inspection
//! without running the full TUI.
//!
//! ## Save semantics
//!
//! On save we create the parent directory (`~/.config/tuipo/`) if it
//! doesn't exist, then write the TOML atomically: write to
//! `config.toml.tmp` and rename, so a crash mid-write can't leave a
//! half-file. The TOML is generated by `Config::to_toml_string` — see
//! `src/config.rs`.

use std::io::{self, Write};
use std::path::PathBuf;
use std::time::Duration;
use std::time::Instant;

use crossterm::cursor::{Hide, MoveTo, Show};
use crossterm::event::{Event, KeyCode, KeyEvent, KeyModifiers};
use crossterm::style::{
    Attribute, Color, Print, ResetColor, SetAttribute, SetForegroundColor,
};
use crossterm::terminal::{
    Clear, ClearType, EnterAlternateScreen, LeaveAlternateScreen, disable_raw_mode,
    enable_raw_mode,
};
use crossterm::{event, execute, queue};

use crate::config::{self, Config, UnderlineMode};

const TITLE: &str = "tuipo config";

/// Entry point. Returns a process exit code.
pub fn run(args: &[String]) -> i32 {
    let mut dry_run = false;
    for arg in args {
        match arg.as_str() {
            "--print" => return print_config(),
            "--path" => return print_path(),
            "--dry-run" => dry_run = true,
            "--help" | "-h" => {
                print_help();
                return 0;
            }
            other => {
                eprintln!("tuipo config: unknown argument: {other}");
                print_help();
                return 1;
            }
        }
    }
    run_tui(dry_run)
}

fn print_help() {
    println!("tuipo config — interactive editor for ~/.config/tuipo/config.toml");
    println!();
    println!("USAGE:");
    println!("  tuipo config              Open the interactive TUI");
    println!("  tuipo config --print      Print current config as TOML to stdout");
    println!("  tuipo config --path       Print the config file path");
    println!("  tuipo config --dry-run    TUI, but save prints to stdout instead");
}

fn print_config() -> i32 {
    let cfg = Config::load();
    print!("{}", cfg.to_toml_string());
    0
}

fn print_path() -> i32 {
    match config::default_config_path() {
        Some(p) => {
            println!("{}", p.display());
            0
        }
        None => {
            eprintln!("tuipo config: cannot determine config path (HOME unset?)");
            1
        }
    }
}

fn run_tui(dry_run: bool) -> i32 {
    let Some(path) = config::default_config_path() else {
        eprintln!("tuipo config: cannot determine config path (HOME unset?)");
        return 1;
    };
    let cfg = Config::load();
    let state = TuiState::new(cfg, path, dry_run);

    let mut stdout = io::stdout();
    if enable_raw_mode().is_err() {
        eprintln!("tuipo config: failed to enable raw mode");
        return 1;
    }
    let setup = execute!(stdout, EnterAlternateScreen, Hide);
    if setup.is_err() {
        let _ = disable_raw_mode();
        eprintln!("tuipo config: failed to set up terminal");
        return 1;
    }

    let result = run_loop(state, &mut stdout);

    let _ = execute!(stdout, ResetColor, Show, LeaveAlternateScreen);
    let _ = disable_raw_mode();
    match &result {
        RunOutcome::SavedDryRun { toml } => {
            // Print the dry-run TOML after the terminal is restored so it
            // appears below the user's prompt instead of getting eaten by
            // the alt-screen exit.
            print!("{toml}");
        }
        RunOutcome::Error(msg) => {
            // Likewise: surface errors after the alt-screen tear-down,
            // so they appear in the user's actual scrollback.
            eprintln!("tuipo config: {msg}");
        }
        _ => {}
    }
    result.exit_code()
}

#[derive(Debug)]
enum RunOutcome {
    Quit,
    Saved,
    SavedDryRun { toml: String },
    Error(String),
}

impl RunOutcome {
    fn exit_code(&self) -> i32 {
        match self {
            RunOutcome::Quit | RunOutcome::Saved | RunOutcome::SavedDryRun { .. } => 0,
            RunOutcome::Error(_) => 1,
        }
    }
}

/// Logical name of each editable field, in display order. Matches the
/// fields on [`Config`] one-for-one.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Field {
    Paint,
    Underline,
    TabFix,
    Picker,
    StatusRow,
    Grammar,
    PauseMs,
    HoverMs,
    DictPath,
}

impl Field {
    const ALL: &'static [Field] = &[
        Field::Paint,
        Field::Underline,
        Field::TabFix,
        Field::Picker,
        Field::StatusRow,
        Field::Grammar,
        Field::PauseMs,
        Field::HoverMs,
        Field::DictPath,
    ];

    fn label(self) -> &'static str {
        match self {
            Field::Paint => "paint",
            Field::Underline => "underline",
            Field::TabFix => "tab_fix",
            Field::Picker => "picker",
            Field::StatusRow => "status_row",
            Field::Grammar => "grammar",
            Field::PauseMs => "pause_ms",
            Field::HoverMs => "hover_ms",
            Field::DictPath => "dict_path",
        }
    }

    fn description(self) -> &'static str {
        match self {
            Field::Paint => "underline overlay master switch",
            Field::Underline => "style: auto · plain · fancy",
            Field::TabFix => "tab triggers spell-fix",
            Field::Picker => "hover + tab suggestion picker",
            Field::StatusRow => "idle bottom-row issue count",
            Field::Grammar => "narrow grammar lints (agreement, malapropism, eggcorn, usage)",
            Field::PauseMs => "ms idle before painting",
            Field::HoverMs => "ms idle before picker tooltip",
            Field::DictPath => "per-user dict override (~/.config/tuipo/dict.txt by default)",
        }
    }

    /// Is this field editable as free text? (Bools/enums are toggled
    /// via space; text fields go through an explicit edit mode.)
    fn is_text_editable(self) -> bool {
        matches!(self, Field::PauseMs | Field::HoverMs | Field::DictPath)
    }
}

/// Edit mode for the text-editable fields. Owns a small buffer the user
/// types into; commit applies it back to the config.
#[derive(Debug)]
struct EditBuffer {
    field: Field,
    text: String,
}

#[derive(Debug)]
enum Mode {
    Browse,
    Editing(EditBuffer),
    ConfirmDiscard,
    /// Briefly displayed after a successful save. The flash itself is
    /// timed via `TuiState::flash`; this variant just suppresses key
    /// repetition while the flash is visible.
    Saved,
}

struct TuiState {
    cfg: Config,
    original: Config,
    path: PathBuf,
    dry_run: bool,
    selected: usize,
    mode: Mode,
    flash: Option<(String, Instant)>,
}

impl TuiState {
    fn new(cfg: Config, path: PathBuf, dry_run: bool) -> Self {
        Self {
            original: cfg.clone(),
            cfg,
            path,
            dry_run,
            selected: 0,
            mode: Mode::Browse,
            flash: None,
        }
    }

    fn dirty(&self) -> bool {
        !configs_equal(&self.cfg, &self.original)
    }

    fn current_field(&self) -> Field {
        Field::ALL[self.selected]
    }

    fn move_up(&mut self) {
        if self.selected > 0 {
            self.selected -= 1;
        }
    }

    fn move_down(&mut self) {
        if self.selected + 1 < Field::ALL.len() {
            self.selected += 1;
        }
    }

    /// Apply space / left / right semantics: toggle bools, cycle enums,
    /// no-op on text fields (those use the explicit Edit mode).
    fn toggle_current(&mut self, direction: i32) {
        match self.current_field() {
            Field::Paint => self.cfg.paint = !self.cfg.paint,
            Field::TabFix => self.cfg.tab_fix = !self.cfg.tab_fix,
            Field::Picker => self.cfg.picker = !self.cfg.picker,
            Field::StatusRow => self.cfg.status_row = !self.cfg.status_row,
            Field::Grammar => self.cfg.grammar = !self.cfg.grammar,
            Field::Underline => self.cfg.underline = cycle_underline(self.cfg.underline, direction),
            Field::PauseMs | Field::HoverMs | Field::DictPath => {
                // Text fields don't toggle; user must press enter to edit.
            }
        }
    }

    fn enter_edit(&mut self) {
        let field = self.current_field();
        if !field.is_text_editable() {
            // Toggle bools/enums on enter for consistency.
            self.toggle_current(1);
            return;
        }
        let text = match field {
            Field::PauseMs => self.cfg.pause_ms.to_string(),
            Field::HoverMs => self.cfg.hover_ms.to_string(),
            Field::DictPath => self.cfg.dict_path.clone().unwrap_or_default(),
            _ => String::new(),
        };
        self.mode = Mode::Editing(EditBuffer { field, text });
    }

    /// Commit the current edit buffer to the config. Returns true if
    /// the commit succeeded (false → input was rejected, e.g. non-digit
    /// in a numeric field).
    fn commit_edit(&mut self) -> bool {
        let Mode::Editing(ref buf) = self.mode else {
            return false;
        };
        let ok = match buf.field {
            Field::PauseMs => {
                if let Ok(n) = buf.text.parse::<u64>() {
                    self.cfg.pause_ms = n;
                    true
                } else {
                    false
                }
            }
            Field::HoverMs => {
                if let Ok(n) = buf.text.parse::<u64>() {
                    self.cfg.hover_ms = n;
                    true
                } else {
                    false
                }
            }
            Field::DictPath => {
                let trimmed = buf.text.trim();
                self.cfg.dict_path = if trimmed.is_empty() {
                    None
                } else {
                    Some(trimmed.to_string())
                };
                true
            }
            _ => false,
        };
        if ok {
            self.mode = Mode::Browse;
        }
        ok
    }

    fn cancel_edit(&mut self) {
        self.mode = Mode::Browse;
    }

    fn save(&mut self) -> RunOutcome {
        let toml = self.cfg.to_toml_string();
        if self.dry_run {
            return RunOutcome::SavedDryRun { toml };
        }
        if let Err(e) = write_atomic(&self.path, &toml) {
            self.flash = Some((format!("save failed: {e}"), Instant::now()));
            return RunOutcome::Error(e);
        }
        self.original = self.cfg.clone();
        self.mode = Mode::Saved;
        self.flash = Some((format!("saved → {}", self.path.display()), Instant::now()));
        RunOutcome::Saved
    }
}

fn configs_equal(a: &Config, b: &Config) -> bool {
    a.paint == b.paint
        && a.underline == b.underline
        && a.tab_fix == b.tab_fix
        && a.picker == b.picker
        && a.status_row == b.status_row
        && a.grammar == b.grammar
        && a.pause_ms == b.pause_ms
        && a.hover_ms == b.hover_ms
        && a.dict_path == b.dict_path
}

fn cycle_underline(mode: UnderlineMode, direction: i32) -> UnderlineMode {
    let order = [UnderlineMode::Auto, UnderlineMode::Plain, UnderlineMode::Fancy];
    let i = order.iter().position(|m| *m == mode).unwrap_or(0) as i32;
    let n = order.len() as i32;
    let next = (i + direction).rem_euclid(n);
    order[next as usize]
}

/// Atomic write: write to `<path>.tmp`, then rename. Guarantees the
/// file is either fully old or fully new — a crash mid-write can't
/// leave the user with a corrupt half-config.
fn write_atomic(path: &PathBuf, content: &str) -> Result<(), String> {
    if let Some(parent) = path.parent()
        && !parent.exists()
    {
        std::fs::create_dir_all(parent).map_err(|e| format!("mkdir {}: {e}", parent.display()))?;
    }
    let tmp = path.with_extension("toml.tmp");
    std::fs::write(&tmp, content).map_err(|e| format!("write {}: {e}", tmp.display()))?;
    std::fs::rename(&tmp, path).map_err(|e| format!("rename to {}: {e}", path.display()))?;
    Ok(())
}

fn run_loop<W: Write>(mut state: TuiState, out: &mut W) -> RunOutcome {
    loop {
        if draw(&state, out).is_err() {
            return RunOutcome::Error("draw failed".into());
        }
        // Block for an event, with a short timeout so the "Saved ✓" flash
        // can auto-clear after ~1.5s.
        let polled = match event::poll(Duration::from_millis(750)) {
            Ok(v) => v,
            Err(e) => return RunOutcome::Error(format!("event poll: {e}")),
        };
        if !polled {
            // Timeout — clear flash if expired and redraw.
            if let Some((_, t)) = state.flash
                && t.elapsed() > Duration::from_millis(1500)
            {
                state.flash = None;
            }
            continue;
        }
        let Ok(ev) = event::read() else {
            return RunOutcome::Error("event read failed".into());
        };
        if let Event::Key(key) = ev
            && let Some(out) = handle_key(&mut state, key)
        {
            return out;
        }
    }
}

fn handle_key(state: &mut TuiState, key: KeyEvent) -> Option<RunOutcome> {
    // Ctrl-C always quits, regardless of mode. Don't trap the user.
    if key.modifiers.contains(KeyModifiers::CONTROL)
        && matches!(key.code, KeyCode::Char('c'))
    {
        return Some(RunOutcome::Quit);
    }
    match &mut state.mode {
        Mode::Editing(buf) => match key.code {
            KeyCode::Enter => {
                if !state.commit_edit() {
                    state.flash = Some(("invalid value".into(), Instant::now()));
                }
                None
            }
            KeyCode::Esc => {
                state.cancel_edit();
                None
            }
            KeyCode::Backspace => {
                buf.text.pop();
                None
            }
            KeyCode::Char(c) => {
                let numeric = matches!(buf.field, Field::PauseMs | Field::HoverMs);
                if numeric && !c.is_ascii_digit() {
                    return None;
                }
                buf.text.push(c);
                None
            }
            _ => None,
        },
        Mode::ConfirmDiscard => match key.code {
            KeyCode::Char('y') | KeyCode::Char('Y') => Some(RunOutcome::Quit),
            KeyCode::Char('n') | KeyCode::Char('N') | KeyCode::Esc => {
                state.mode = Mode::Browse;
                None
            }
            _ => None,
        },
        Mode::Browse | Mode::Saved => {
            // Drop the saved flash on the first interactive key.
            if matches!(state.mode, Mode::Saved) {
                state.mode = Mode::Browse;
            }
            handle_browse_key(state, key)
        }
    }
}

fn handle_browse_key(state: &mut TuiState, key: KeyEvent) -> Option<RunOutcome> {
    match key.code {
        KeyCode::Up | KeyCode::Char('k') => state.move_up(),
        KeyCode::Down | KeyCode::Char('j') => state.move_down(),
        KeyCode::Char(' ') => state.toggle_current(1),
        KeyCode::Right | KeyCode::Char('l') => state.toggle_current(1),
        KeyCode::Left | KeyCode::Char('h') => state.toggle_current(-1),
        KeyCode::Enter => state.enter_edit(),
        KeyCode::Char('s') => {
            return Some(state.save());
        }
        KeyCode::Char('q') | KeyCode::Esc => {
            if state.dirty() {
                state.mode = Mode::ConfirmDiscard;
            } else {
                return Some(RunOutcome::Quit);
            }
        }
        _ => {}
    }
    None
}

// -------- drawing --------

fn draw<W: Write>(state: &TuiState, out: &mut W) -> io::Result<()> {
    queue!(out, Clear(ClearType::All), MoveTo(0, 0))?;
    // Header.
    queue!(
        out,
        SetAttribute(Attribute::Bold),
        Print(format!("  {TITLE}")),
        SetAttribute(Attribute::Reset),
    )?;
    queue!(
        out,
        MoveTo(0, 1),
        SetForegroundColor(Color::DarkGrey),
        Print(format!("  {}", state.path.display())),
        ResetColor,
    )?;
    if state.dirty() {
        queue!(
            out,
            MoveTo(60, 1),
            SetForegroundColor(Color::Yellow),
            Print("● modified"),
            ResetColor,
        )?;
    }
    if state.dry_run {
        queue!(
            out,
            MoveTo(74, 1),
            SetForegroundColor(Color::Cyan),
            Print("(dry-run)"),
            ResetColor,
        )?;
    }
    // Fields.
    for (i, field) in Field::ALL.iter().enumerate() {
        let row = (3 + i) as u16;
        let is_selected = i == state.selected;
        draw_field(out, state, *field, row, is_selected)?;
    }
    // Divider + help.
    let divider_row = (3 + Field::ALL.len() + 1) as u16;
    queue!(
        out,
        MoveTo(0, divider_row),
        SetForegroundColor(Color::DarkGrey),
        Print(format!("  {}", "─".repeat(74))),
        ResetColor,
    )?;
    let help_row = divider_row + 1;
    queue!(out, MoveTo(0, help_row), SetForegroundColor(Color::DarkGrey))?;
    match &state.mode {
        Mode::Browse | Mode::Saved => {
            queue!(
                out,
                Print(
                    "  ↑/↓ move    space toggle    enter edit    s save    q quit    ctrl-c exit",
                ),
            )?;
        }
        Mode::Editing(buf) => {
            let hint = if matches!(buf.field, Field::PauseMs | Field::HoverMs) {
                "  type a number    enter commit    esc cancel"
            } else {
                "  type a path    enter commit    esc cancel    (empty = use default)"
            };
            queue!(out, Print(hint))?;
        }
        Mode::ConfirmDiscard => {
            queue!(
                out,
                SetForegroundColor(Color::Yellow),
                Print("  unsaved changes — discard and quit? (y/n)"),
            )?;
        }
    }
    queue!(out, ResetColor)?;
    if let Some((msg, t)) = &state.flash
        && t.elapsed() < Duration::from_millis(1500)
    {
        let status_row = help_row + 2;
        let color = if msg.starts_with("save failed") || msg == "invalid value" {
            Color::Red
        } else {
            Color::Green
        };
        queue!(
            out,
            MoveTo(0, status_row),
            SetForegroundColor(color),
            Print(format!("  {msg}")),
            ResetColor,
        )?;
    }
    out.flush()
}

fn draw_field<W: Write>(
    out: &mut W,
    state: &TuiState,
    field: Field,
    row: u16,
    selected: bool,
) -> io::Result<()> {
    let marker_col = 2u16;
    let name_col = 4u16;
    let value_col = 20u16;
    let desc_col = 42u16;

    // Selection marker.
    queue!(out, MoveTo(marker_col, row))?;
    if selected {
        queue!(out, SetForegroundColor(Color::Cyan), Print("▸"), ResetColor)?;
    } else {
        queue!(out, Print(" "))?;
    }
    // Field name.
    queue!(out, MoveTo(name_col, row))?;
    if selected {
        queue!(out, SetAttribute(Attribute::Bold))?;
    }
    queue!(out, Print(field.label()))?;
    if selected {
        queue!(out, SetAttribute(Attribute::Reset))?;
    }
    // Value.
    queue!(out, MoveTo(value_col, row))?;
    let value_text = render_value(state, field);
    let value_color = value_color_for(state, field);
    if let Some(c) = value_color {
        queue!(out, SetForegroundColor(c))?;
    }
    queue!(out, Print(value_text))?;
    if value_color.is_some() {
        queue!(out, ResetColor)?;
    }
    // Description.
    queue!(
        out,
        MoveTo(desc_col, row),
        SetForegroundColor(Color::DarkGrey),
        Print(field.description()),
        ResetColor,
    )?;
    Ok(())
}

fn render_value(state: &TuiState, field: Field) -> String {
    // If we're editing this field, show the edit buffer with a fake
    // cursor at the end so the user has visual feedback.
    if let Mode::Editing(buf) = &state.mode
        && buf.field == field
    {
        return format!("{}_", buf.text);
    }
    match field {
        Field::Paint => bool_label(state.cfg.paint),
        Field::Underline => match state.cfg.underline {
            UnderlineMode::Auto => "auto".into(),
            UnderlineMode::Plain => "plain".into(),
            UnderlineMode::Fancy => "fancy".into(),
        },
        Field::TabFix => bool_label(state.cfg.tab_fix),
        Field::Picker => bool_label(state.cfg.picker),
        Field::StatusRow => bool_label(state.cfg.status_row),
        Field::Grammar => bool_label(state.cfg.grammar),
        Field::PauseMs => state.cfg.pause_ms.to_string(),
        Field::HoverMs => state.cfg.hover_ms.to_string(),
        Field::DictPath => state
            .cfg
            .dict_path
            .clone()
            .unwrap_or_else(|| "(default)".into()),
    }
}

fn value_color_for(state: &TuiState, field: Field) -> Option<Color> {
    // Editing → cyan to draw attention to the active field.
    if let Mode::Editing(buf) = &state.mode
        && buf.field == field
    {
        return Some(Color::Cyan);
    }
    let on = match field {
        Field::Paint => Some(state.cfg.paint),
        Field::TabFix => Some(state.cfg.tab_fix),
        Field::Picker => Some(state.cfg.picker),
        Field::StatusRow => Some(state.cfg.status_row),
        Field::Grammar => Some(state.cfg.grammar),
        _ => None,
    };
    on.map(|v| if v { Color::Green } else { Color::DarkGrey })
}

fn bool_label(v: bool) -> String {
    if v { "on" } else { "off" }.into()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn s_path() -> PathBuf {
        PathBuf::from("/tmp/tuipo-test/config.toml")
    }

    #[test]
    fn cycle_underline_visits_all_three() {
        assert_eq!(cycle_underline(UnderlineMode::Auto, 1), UnderlineMode::Plain);
        assert_eq!(cycle_underline(UnderlineMode::Plain, 1), UnderlineMode::Fancy);
        assert_eq!(cycle_underline(UnderlineMode::Fancy, 1), UnderlineMode::Auto);
        // Reverse direction.
        assert_eq!(cycle_underline(UnderlineMode::Auto, -1), UnderlineMode::Fancy);
    }

    #[test]
    fn dirty_flag_tracks_changes() {
        let cfg = Config::default();
        let mut s = TuiState::new(cfg, s_path(), true);
        assert!(!s.dirty(), "fresh state is not dirty");
        s.toggle_current(1); // toggle paint (selected = 0 by default)
        assert!(s.dirty());
    }

    #[test]
    fn toggle_bools_inverts_value() {
        let mut s = TuiState::new(Config::default(), s_path(), true);
        let before = s.cfg.paint;
        s.toggle_current(1);
        assert_ne!(s.cfg.paint, before);
        s.toggle_current(-1);
        assert_eq!(s.cfg.paint, before);
    }

    #[test]
    fn enter_edit_on_text_field_opens_buffer() {
        let mut s = TuiState::new(Config::default(), s_path(), true);
        // Move to pause_ms (index 6 after Grammar was inserted at 5).
        for _ in 0..6 {
            s.move_down();
        }
        assert_eq!(s.current_field(), Field::PauseMs);
        s.enter_edit();
        match &s.mode {
            Mode::Editing(buf) => {
                assert_eq!(buf.field, Field::PauseMs);
                assert_eq!(buf.text, "150");
            }
            _ => panic!("expected Editing mode, got {:?}", s.mode),
        }
    }

    #[test]
    fn commit_numeric_edit_writes_back() {
        let mut s = TuiState::new(Config::default(), s_path(), true);
        for _ in 0..6 {
            s.move_down();
        } // pause_ms (Grammar pushed the index one slot down)
        s.enter_edit();
        // Wipe + retype.
        if let Mode::Editing(buf) = &mut s.mode {
            buf.text.clear();
            buf.text.push_str("400");
        }
        assert!(s.commit_edit());
        assert_eq!(s.cfg.pause_ms, 400);
        assert!(matches!(s.mode, Mode::Browse));
    }

    #[test]
    fn commit_invalid_numeric_keeps_editing() {
        let mut s = TuiState::new(Config::default(), s_path(), true);
        for _ in 0..6 {
            s.move_down();
        }
        s.enter_edit();
        if let Mode::Editing(buf) = &mut s.mode {
            buf.text.clear();
            buf.text.push_str("nope");
        }
        assert!(!s.commit_edit(), "non-numeric input should reject");
        assert!(matches!(s.mode, Mode::Editing(_)));
    }

    #[test]
    fn commit_dict_path_clears_to_none_when_empty() {
        let mut s = TuiState::new(
            Config {
                dict_path: Some("/tmp/words".into()),
                ..Config::default()
            },
            s_path(),
            true,
        );
        for _ in 0..8 {
            s.move_down();
        } // dict_path (after Grammar insertion the index shifted from 7 to 8)
        s.enter_edit();
        if let Mode::Editing(buf) = &mut s.mode {
            buf.text.clear();
        }
        assert!(s.commit_edit());
        assert!(
            s.cfg.dict_path.is_none(),
            "empty input should restore default"
        );
    }

    #[test]
    fn render_value_for_dict_path_shows_default_when_none() {
        let s = TuiState::new(Config::default(), s_path(), true);
        let v = render_value(&s, Field::DictPath);
        assert_eq!(v, "(default)");
    }

    #[test]
    fn write_atomic_creates_parent_and_writes() {
        let dir = std::env::temp_dir().join(format!(
            "tuipo-tui-test-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0),
        ));
        let path = dir.join("nested").join("config.toml");
        let _ = std::fs::remove_dir_all(&dir);
        write_atomic(&path, "paint = false\n").expect("write_atomic");
        let read = std::fs::read_to_string(&path).expect("read");
        assert_eq!(read, "paint = false\n");
        let _ = std::fs::remove_dir_all(&dir);
    }
}
